# * 반복문 / 함수

## # 반복문 

### for문

- 리스트, 튜플, 문자열 등의 값들을 변수로 사용해 명령문을 반복 수행
- While문과 비슷하지만 다양한 자료구조를 설정 후 명령문 블록이 실행

In [1]:
num_list = [1,2,3,4,5]

In [2]:
for num in num_list:
    print(num)

1
2
3
4
5


In [7]:
for looper in [1,2,3,4,5]:
    print("hello")

hello
hello
hello
hello
hello


In [8]:
for looper in [1,2,3,4,5]:
    print(looper)

1
2
3
4
5


In [10]:
for i in range(100):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [11]:
for i in 'abcdefg':
    print(i)

a
b
c
d
e
f
g


In [13]:
for i in range(0,5):
    print(i)

0
1
2
3
4


In [14]:
for i in range(5):
    print(i)

0
1
2
3
4


In [15]:
for i in ['americano','latte','frafuchino']:
    print(i)

americano
latte
frafuchino


In [17]:
for i in range(1,10,2):
    print(i)

1
3
5
7
9


In [21]:
gugudan = int(input())
print("구구단" + str(gugudan) + "단을 계산합니다.")

for i in range(1,10):
    print(str(gugudan) + "*" + str(i) + "=" + str(gugudan*i))

5
구구단5단을 계산합니다.
5*1=5
5*2=10
5*3=15
5*4=20
5*5=25
5*6=30
5*7=35
5*8=40
5*9=45


In [2]:
gugudan = str(input())

print("구구단" + str(gugudan) + "단을 계산합니다.")

for i in range(1,10):
    print(str(gugudan) + "*" + int(i) + "=" + str(gugudan*i))

5
구구단5단을 계산합니다.


TypeError: must be str, not int

In [1]:
gugudan = int(input())

print("구구단" + str(gugudan) + "단을 계산합니다.")

for i in range(1,10):
    print(str(gugudan) + "*" + int(i) + "=" + str(gugudan*i))

3
구구단3단을 계산합니다.


TypeError: must be str, not int

In [26]:
for i in range(3,30,3):
    print(i)

3
6
9
12
15
18
21
24
27


### While문

- 조건에 만족하는 값이 나올 때까지 명령문들을 반복 수행
- While문이 시작한 행은 반복문의 헤더라 칭한다.
- 헤더의 조건을 비교해 while문의 몸통부분에 대해 코드를 조건에 만족하는 값이 나올 때까지 반복적으로 수행
- 코드의 ‘들여쓰기한 명령문1’ 블록을 몸통이라고 한다.

In [29]:
i = 1
while i < 10:
    print(i)
    i += 1

1
2
3
4
5
6
7
8
9


In [30]:
for i in range(10):
    if i == 5: break
    print(i)
print("EOP")

0
1
2
3
4
EOP


In [31]:
for i in range(10):
    print(i),
else:
    print("EOP")

0
1
2
3
4
5
6
7
8
9
EOP


In [33]:
i = 1
while i < 10:
    print(i),
    i += 1
else:
    print("EOP")

1
2
3
4
5
6
7
8
9
EOP


# # 함수

- 함수는 재사용 가능한 프로그램을 의미
- def를 통해 함수를 정의할 수 있다.
- Return을 사용해 최종적으로 사용할 값을 반환
- 함수도 이전의 조건문과 같이 들여쓰기 4칸을 이용해 함수 블록을 생성 후 안에서 작업이 가능

In [39]:
#-*- coding: utf-8 -*-
def calculateRectangleArea(x , y): # 사각형의 넓이를 구하는 함수
    return x * y
rectangle_x = 10
rectangle_y = 20
print ("사각형 x의 길이: ", rectangle_x)
print ("사각형 y의 길이: ", rectangle_y)
print ("사각형의 넓이: ", calculateRectangleArea(rectangle_x, rectangle_y)) #넓이를 구하는 함수 호출

사각형 x의 길이:  10
사각형 y의 길이:  20
사각형의 넓이:  200


In [42]:
def a_rectangleArea(): # 인자 X , 리턴 값 X,
    print(5 * 7) # 넓이를 계산하여 함수 내에서 출력

def b_rectangleArea(x,y): # 인자 O , 리턴 값 X,
    print(x * y) # 인자 값으로 넓이를 계산, 함수 내에서 출력

def c_rectangleArea(): # 인자 X , 리턴 값 O
    return(5 * 7) # 넓이를 계산하여 결과 값 반환

def d_rectangleArea(x ,y): # 인자 O , 리턴 값 O,
    return(x * y) # 인자 값으로 넓이를 계산, 결과 값 반환

a_rectangleArea()

b_rectangleArea(5,7)

print(c_rectangleArea()) # 반환 값이 있으면 반환 값을 사용

print(d_rectangleArea(5,7))

35
35
35
35


In [4]:
def spam(eggs):
    eggs.append(1) # 기존 객체의 주소값에 [1] 추가
    eggs = [2, 3] # 새로운 객체 생성

ham = [0]
spam(ham)
print(ham)

[0, 1]


In [5]:
def test(t):
    t = 20
    print ("In Function :", t)
    
x = 10
print ("Before :", x) # 10

test(x) # 함수 호출
print("After :", x) # 10 – 함수내부의 t는 새로운 주소값을 가짐

Before : 10
In Function : 20
After : 10


In [11]:
def test(t):
    t = 20
    print ("In Function :", t)
    
x = 10
print ("Before :", x) # 10

test(x) # 함수 호출
print("After :", x) # 10 – 함수내부의 t는 새로운 주소값을 가짐

Before : 10
In Function : 20
After : 10


In [9]:
test(4)

In Function : 20


In [8]:
def calculate(x, y):
    total = x + y # 새로운 값이 할당되어 함수내 total은 지역변수가 됨
    print ("In Function")
    print ("a:", str(a), "b:", str(b), "a+b:", str(a+b), "total :", str(total))
    return total

a = 5 # a와 b는 전역변수
b = 7
total = 0 # 전역변수 total

print ("In Program - 1")
print ("a:", str(a), "b:", str(b), "a+b:", str(a+b))

sum = calculate (a,b)
print("After Calculation")
print("Total :", str(total), " Sum:", str(sum)) # 지역변수는 전역변수에 영향 X

In Program - 1
a: 5 b: 7 a+b: 12
In Function
a: 5 b: 7 a+b: 12 total : 12
After Calculation
Total : 0  Sum: 12


In [10]:
calculate(5,7)

In Function
a: 5 b: 7 a+b: 12 total : 12


12

#### swap 

In [34]:
def swap_value (x, y):
    temp = x
    x = y
    y = temp
    
def swap_offset (offset_x, offset_y):
    temp = a[offset_x]
    a[offset_x] = a[offset_y]
    a[offset_y] = temp

def swap_reference (list, offset_x, offset_y):
    temp = list[offset_x]
    list[offset_x] = list[offset_y]
    list[offset_y] = temp

In [35]:
a = [1,2,3,4,5] 

In [36]:
swap_value(a[1], a[2]) 
print(a) # [1,2,3,4,5] 

[1, 2, 3, 4, 5]


In [37]:
swap_offset(1,2) 
print(a) # [1,3,2,4,5] 

[1, 3, 2, 4, 5]


In [38]:
swap_reference(a, 1, 2) 
print(a) # [1,3,2,4,5]

[1, 2, 3, 4, 5]


In [39]:
a[1]

2

In [17]:
a[2]

3

In [26]:
a = [1,2,3,4,5]

In [27]:
swap_value(2,3)
print(a)

[1, 2, 3, 4, 5]


In [22]:
swap_offset(3,2)

In [23]:
swap_reference(a, 1, 2)

In [14]:
a

[1, 2, 3, 4, 5]

# # 람다(lambda)

# # 패키지 및 라이브러리 

## 모듈 & 라이브러리

In [43]:
#난수
import random
print(random.randint (0,100)) # 0~100사이의 정수 난수를 생성
print(random.random) # 일반적인 난수 생성

33
<built-in method random of Random object at 0x0000000002AF4F48>


In [44]:
#시간
import time
time.localtime() # 현재 시간 출력

time.struct_time(tm_year=2018, tm_mon=7, tm_mday=4, tm_hour=13, tm_min=20, tm_sec=21, tm_wday=2, tm_yday=185, tm_isdst=0)

#  # Numpy

행렬 계산

In [51]:
import numpy as np

In [52]:
exam = np.array([1,2,3,4,5])

In [53]:
exam

array([1, 2, 3, 4, 5])

In [58]:
exam = [[1]*2 for i in range(3)]

EXAM = np.array(exam)

In [59]:
exam

[[1, 1], [1, 1], [1, 1]]

In [60]:
EXAM

array([[1, 1],
       [1, 1],
       [1, 1]])

In [61]:
EXAM.shape

(3, 2)

- Ndarry 기본 연산 ndarray의 기본 연산은 배열 연산을 기본으로 지원 
- Python list의 경우 +. * 연산이 지원되며 이 연산은 list 원소를 con caternate하는 역핛을 함

In [62]:
exam = [1,2,3,4,5]
print(exam + exam)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [63]:
print(exam*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [64]:
exam = np.array([1,2,3,4,5])
print(exam*2)

[ 2  4  6  8 10]


In [65]:
print(exam + 2)

[3 4 5 6 7]


In [66]:
print(exam - 2)

[-1  0  1  2  3]


In [67]:
print(exam / 2)

[0.5 1.  1.5 2.  2.5]


In [68]:
print(exam ** 2)

[ 1  4  9 16 25]


- Ndarry indexing 연산 ndarray 또핚 파이썬 기본 list처럼 읶덱스 연산을 지원 
- Ndarray[begin : end]로 접근 가능 
- 2차원 ndarray는 ndarray[begin : end, begin : end]로 접근 가능 
- : 는 전체를 선택하는 연산

In [70]:
exam = np.array([[1,2,3], [4,5,6,], [7,8,9]])
print(exam)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [71]:
exam[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [72]:
exam[1:3, 1:3]

array([[5, 6],
       [8, 9]])

- Ndarry 연산을 통한 True, False 값을 이용하여 indexing할 수 잇음

In [73]:
exam1 = np.array([1,2,3,4,5])
exam2 = np.array(['하나', '둘', '셋', '넷', '다섯'])

print(exam1 > 3)

[False False False  True  True]


In [74]:
print(exam2[exam1 > 3])

['넷' '다섯']


##### 실습

In [82]:
exam = np.array([[1,2,3], [4,5,6,], [7,8,9]])

In [83]:
exam

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
exam[1]

array([4, 5, 6])

In [95]:
exam[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [94]:
exam[2]

array([7, 8, 9])

In [92]:
exam[0]

array([1, 2, 3])

In [90]:
exam[:, 1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [98]:
exam[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

- np.mean() : ndarray 원소 젂체의 평균값을 반환
- np.median() : ndarray 원소 젂체의 중갂 값을 반환
- np.std() : ndarray 원소 젂체의 표준편차를 반환
- np.corrcoef(A, B) : A array와 B array의 correlation coefficient를 반환

In [99]:
exam = [1,2,3,4,5,6,7,8,9,10]

In [100]:
print(np.mean(exam))

5.5


In [101]:
print(np.median(exam))

5.5


In [102]:
print(np.std(exam))

2.8722813232690143


In [103]:
print(np.max(exam))

10


In [104]:
print(np.min(exam))

1


In [106]:
exam1 = [1,2,3,4,5,6,7,8,9,10]

exam2 = [5,6,7,8,9,10,11,12,13,14]

exam3 = [10,9,8,7,6,5,4,3,2,1]

exam4 = [20,17,13,5,6,2,14,23,9,10]

exam5 = [5,6,7]

In [107]:
print(np.corrcoef(exam1, exam2))

[[1. 1.]
 [1. 1.]]


In [108]:
print(np.corrcoef(exam1, exam3))

[[ 1. -1.]
 [-1.  1.]]


In [109]:
print(np.corrcoef(exam1, exam4))

[[ 1.         -0.19776227]
 [-0.19776227  1.        ]]


- numpy에서 제공하는 함수를 사용하여 numpy 배열을 맊드는 방법을 알아봄 

- 이러한 기능을 제공하는 함수로는 zeros(), ones(), full(), eye() 등이 잇는데, zeros()는 해당 배열에 모두 0을 집어 넣고, ones()는 모두 1을 집어 넣음 

- full()은 배열에 사용자가 지정핚 값을 넣는데 사용하고, eye()는 대각선으로는 1이고 나머지는 0읶 2차원 배열을 생성 

- 예제는 이들 함수들을 사용하여 numpy 배열을 생성한 예 

- 그리고 마지막 예는 0부터 n-1 까지의 숫자를 생성하는 range(n) 함수와 배열을 다차원으로 변형하는 reshape()를 통해 갂단하게 샘플 배열을 생성해 본 것

In [110]:
exam = np.zeros([3,3])
print(exam)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [112]:
exam = np.ones((3,3))
print(exam)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [113]:
exam = np.full([3,3], 7)
print(exam)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [114]:
exam = np.full([3,3], 7.0)
print(exam)

[[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]


In [115]:
exam = np.eye(7)
print(exam)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [116]:
exam = np.array(range(10))
print(exam)

[0 1 2 3 4 5 6 7 8 9]


In [118]:
exam = np.array(range(10)).reshape(5,2)
print(exam)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [120]:
exam = np.array(range(10)).reshape(-1,1)
print(exam)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [122]:
exam = np.array(range(10)).reshape(1,-1)
print(exam)

[[0 1 2 3 4 5 6 7 8 9]]


- numpy은 배열값 연산을 위해 많은 함수들을 제공 
- 예를 들어, 각 배열 요소들을 더하는 sum() 함수, 각 배열 요소들을 곱하는 prod() 함수 등을 사용할 수 잇음 
- 이들 함수에 선택옵션으로 axis 을 지정할 수 있는데, 예를 들어 sum()에서 axis가 1이면 행끼리 더하는 것이고, axis가 0 이면 열끼리 더하는 것

In [123]:
exam = np.array([[1,2,3], [4,5,6]])

In [124]:
print(np.sum(exam))

21


In [125]:
print(np.sum(exam, axis = 0))

[5 7 9]


In [126]:
print(np.sum(exam, axis = 1))

[ 6 15]


In [127]:
print(np.prod(exam))

720


NumPy는 Numerical Python의 약자로 배열 또는 다양핚 자료구조를 다룰 수 잇는 클래스들을 포함하고 잇는 패키지

### List를 사용한 배열

- 다수의 List를 이용해 다차원의 배열을 쉽게 생성 
- 다차원 배열은 다수의 List를 하나로 묶은 배열

#### List 자료형을 이용한 다차원 배열

In [129]:
np = [1.0, 10.4, 3.2, 5.1, 7.5, 2.7]

flotV = [np, np, np]
flotV

[[1.0, 10.4, 3.2, 5.1, 7.5, 2.7],
 [1.0, 10.4, 3.2, 5.1, 7.5, 2.7],
 [1.0, 10.4, 3.2, 5.1, 7.5, 2.7]]

In [130]:
flotV[0]

[1.0, 10.4, 3.2, 5.1, 7.5, 2.7]

In [131]:
flotV[0] = 'Python'
flotV

['Python', [1.0, 10.4, 3.2, 5.1, 7.5, 2.7], [1.0, 10.4, 3.2, 5.1, 7.5, 2.7]]

# # Pandas 

In [132]:
import pandas as pd

데이터프레임

- 데이터 정제와 젂처리에 유용한 Python 오픈소스 라이브러리 
- 시각화 기능도 제공하고 잇음 
- 다양한 형태의 데이터를 다룰 수 잇음

### Series

- value와 index 형태를 갖는 1차원 자료구조 
- Series는 Numpy의 array와 유사한 형식 
- Numpy의 array와 차이점: Series는 axis label이 있음 
- axis label이 잇다는 것은 단순 위치 정보 뿐만 아니라, label을 사용해 indexing이 가능하다는 것을 의미 
- 또 다른 차이점은 numeric data 뿐만 아니라 다양한 자료형을 저장할 수 잇다는 것

#### (1) List를 사용한 Series 생성

In [147]:
labels = ['a','b','c']
mylist = [10, 20, 30]
print(mylist)

[10, 20, 30]


In [134]:
pd.Series(data=mylist)

0    10
1    20
2    30
dtype: int64

In [135]:
pd.Series(data=mylist, index=labels)

a    10
b    20
c    30
dtype: int64

In [136]:
pd.Series(mylist, labels)

a    10
b    20
c    30
dtype: int64

#### (2) Numpy Array를 사용한 Series 생성

In [141]:
import numpy as np

In [142]:
arr = np.array(mylist)
print(arr)

[10 20 30]


In [143]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [144]:
pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int32

#### (3) Dictionary를 사용한 Series 생성

In [145]:
d = {'a':10, 'b':20, 'c':30}
print(d)

{'a': 10, 'b': 20, 'c': 30}


In [146]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

#### Using an Index

In [148]:
ser1 = pd.Series([1,2,3,4], index = ['USA','Germany', 'USSR', 'Japan'])

In [149]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [150]:
ser1['USA']

1

### DataFrame

- DataFrame은 Pandas에서 제공하는 강력한 기능 
- 동일한 index를 가지고 잇는 series들의 묶음으로 쉽게 생각할 수 있음

#### (1) 데이터 생성하기

In [151]:
import pandas as pd
import numpy as np

In [152]:
data = np.random.randn(5,4)
data

array([[ 1.92903672,  0.1851275 ,  0.76232859,  0.46531356],
       [ 1.18645249, -0.00527285,  0.81139414, -0.79061976],
       [ 2.05665741, -0.12820775, -0.90202338, -0.49830432],
       [-0.45040824, -0.341328  , -0.06530952, -0.12327061],
       [-0.01071197, -1.50588791,  0.36328469, -0.17181197]])

In [153]:
df = pd.DataFrame(data, index = ['A','B','C','D','E'], columns = ['W','X','Y','Z'])

In [154]:
df

W         X         Y         Z
A  1.929037  0.185127  0.762329  0.465314
B  1.186452 -0.005273  0.811394 -0.790620
C  2.056657 -0.128208 -0.902023 -0.498304
D -0.450408 -0.341328 -0.065310 -0.123271
E -0.010712 -1.505888  0.363285 -0.171812

#### (2) DataFrame 내부 특정 데이터 추출하기

In [155]:
df['W']

A    1.929037
B    1.186452
C    2.056657
D   -0.450408
E   -0.010712
Name: W, dtype: float64

In [158]:
df[['W','Z']]

W         Z
A  1.929037  0.465314
B  1.186452 -0.790620
C  2.056657 -0.498304
D -0.450408 -0.123271
E -0.010712 -0.171812

In [159]:
type(df['W'])

pandas.core.series.Series

#### (3) 새로운 컬럼 생성하기

In [160]:
df['W'] + df['Z']

A    2.394350
B    0.395833
C    1.558353
D   -0.573679
E   -0.182524
dtype: float64

In [162]:
df['new'] = df['W'] + df['Z']
print(df)

          W         X         Y         Z       new
A  1.929037  0.185127  0.762329  0.465314  2.394350
B  1.186452 -0.005273  0.811394 -0.790620  0.395833
C  2.056657 -0.128208 -0.902023 -0.498304  1.558353
D -0.450408 -0.341328 -0.065310 -0.123271 -0.573679
E -0.010712 -1.505888  0.363285 -0.171812 -0.182524


#### (4) 열(컬럼) 삭제하기

In [163]:
df.drop('new', axis=1)

W         X         Y         Z
A  1.929037  0.185127  0.762329  0.465314
B  1.186452 -0.005273  0.811394 -0.790620
C  2.056657 -0.128208 -0.902023 -0.498304
D -0.450408 -0.341328 -0.065310 -0.123271
E -0.010712 -1.505888  0.363285 -0.171812

In [165]:
df # 원본 데이터는 변형되지 않음

W         X         Y         Z       new
A  1.929037  0.185127  0.762329  0.465314  2.394350
B  1.186452 -0.005273  0.811394 -0.790620  0.395833
C  2.056657 -0.128208 -0.902023 -0.498304  1.558353
D -0.450408 -0.341328 -0.065310 -0.123271 -0.573679
E -0.010712 -1.505888  0.363285 -0.171812 -0.182524

In [166]:
df.drop('new', axis=1, inplace=True)
df

W         X         Y         Z
A  1.929037  0.185127  0.762329  0.465314
B  1.186452 -0.005273  0.811394 -0.790620
C  2.056657 -0.128208 -0.902023 -0.498304
D -0.450408 -0.341328 -0.065310 -0.123271
E -0.010712 -1.505888  0.363285 -0.171812

#### (5) 행 삭제하기

In [167]:
df.drop('E',axis=0)

W         X         Y         Z
A  1.929037  0.185127  0.762329  0.465314
B  1.186452 -0.005273  0.811394 -0.790620
C  2.056657 -0.128208 -0.902023 -0.498304
D -0.450408 -0.341328 -0.065310 -0.123271

In [168]:
df

W         X         Y         Z
A  1.929037  0.185127  0.762329  0.465314
B  1.186452 -0.005273  0.811394 -0.790620
C  2.056657 -0.128208 -0.902023 -0.498304
D -0.450408 -0.341328 -0.065310 -0.123271
E -0.010712 -1.505888  0.363285 -0.171812

#### (6) 행 선택하기

loc : index label로 데이터 호출

In [169]:
df.loc['A']

W    1.929037
X    0.185127
Y    0.762329
Z    0.465314
Name: A, dtype: float64

iloc : index의 position을 기준으로 데이터 호출

In [170]:
df.iloc[2]

W    2.056657
X   -0.128208
Y   -0.902023
Z   -0.498304
Name: C, dtype: float64

#### (7) 특정 부분의 데이터 호출하기

In [171]:
df.loc['B','Y']

0.8113941393563185

In [172]:
df.loc[['A','B'],['W','Y']]

W         Y
A  1.929037  0.762329
B  1.186452  0.811394

### Conditional Selection

#### (1) 조건에 맞는 데이터 추출

In [173]:
df

W         X         Y         Z
A  1.929037  0.185127  0.762329  0.465314
B  1.186452 -0.005273  0.811394 -0.790620
C  2.056657 -0.128208 -0.902023 -0.498304
D -0.450408 -0.341328 -0.065310 -0.123271
E -0.010712 -1.505888  0.363285 -0.171812

In [174]:
df>0

W      X      Y      Z
A   True   True   True   True
B   True  False   True  False
C   True  False  False  False
D  False  False  False  False
E  False  False   True  False

In [175]:
df[df>0]

W         X         Y         Z
A  1.929037  0.185127  0.762329  0.465314
B  1.186452       NaN  0.811394       NaN
C  2.056657       NaN       NaN       NaN
D       NaN       NaN       NaN       NaN
E       NaN       NaN  0.363285       NaN

In [176]:
df[df['W']>0]

W         X         Y         Z
A  1.929037  0.185127  0.762329  0.465314
B  1.186452 -0.005273  0.811394 -0.790620
C  2.056657 -0.128208 -0.902023 -0.498304

In [177]:
df[df['W']>0]['Y']

A    0.762329
B    0.811394
C   -0.902023
Name: Y, dtype: float64

In [179]:
df[df['W']>0][['Y','X']]

Y         X
A  0.762329  0.185127
B  0.811394 -0.005273
C -0.902023 -0.128208

### Operations

- DataFrame에서 사용핛 수 잇는 다양핚 함수 살펴보기

In [181]:
import pandas as pd

df = pd.DataFrame({'col1':[1,2,3,4], 'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

### 기본 함수

#### (1) head()

In [182]:
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

#### (2) Info on unique values

In [183]:
df['col2'].unique()

array([444, 555, 666], dtype=int64)

In [184]:
df['col2'].nunique()

3

#### (3) del(컬럼삭제)

In [185]:
del df['col1']

In [186]:
df

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

#### (4) columns, index

In [187]:
df.columns

Index(['col2', 'col3'], dtype='object')

In [188]:
df.index

RangeIndex(start=0, stop=4, step=1)

#### Missing Data 처리 

- 누락된 데이터(null/NaN) 처리 
- Null : 값이 없음 
- NaN : Not a Number, 연산 오류 (ex 0 / 0)

#### (1) Null 값 확인

In [190]:
df = pd.DataFrame({'A' : [1,2,np.nan],
                  'B' : [5, np.nan, np.nan],
                  'C' : [1,2,3]})

In [191]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [192]:
df.isnull()

A      B      C
0  False  False  False
1  False   True  False
2   True   True  False

#### (2) Null / NaN 값 포함하는 행 또는 열 삭제

In [193]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [194]:
df.dropna(axis=1)

C
0  1
1  2
2  3

#### (3) Null / NaN 값 대체

In [197]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [196]:
df.fillna(0)

A    B  C
0  1.0  5.0  1
1  2.0  0.0  2
2  0.0  0.0  3

### Groupby

#### (1) 데이터 생성하기

In [199]:
import pandas as pd 
data = {'Company' : ['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
       'Person': ['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
       'Sales' : [200, 120, 340, 124, 243, 350]}

In [200]:
df = pd.DataFrame(data)
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

#### (2) Company를 key값으로 그룹화

In [208]:
by_comp = df.groupby("Company")

In [209]:
by_comp.mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [210]:
df.groupby("Company").mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [211]:
df.groupby("Company").std()

Sales
Company            
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [212]:
df.groupby("Company").min()

Person  Sales
Company                
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [213]:
df.groupby("Company").max()

Person  Sales
Company                
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [214]:
by_comp.count()

Person  Sales
Company               
FB            2      2
GOOG          2      2
MSFT          2      2

In [215]:
by_comp.describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

### Merging, Joining and Concatenating

- 두 개 이상의 데이터프레임을 합치는 세 가지 방법 
- Merge : 두 데이터프레임의 공통 열 혹은 읶덱스를 Key 값으로 하며 이를 기준으로 두 개의 테이블을 합친다. 
- Join : Merge와 동일하게 사용할 수 잇다. 
- Concat : Merge나 Join과 같이 기준 값(key)을 사용하지 않고 단순히 데이터를 연결한다. 기본적으로는 위/아래로 데이터 행을 연결한다.

In [216]:
import pandas as pd

In [223]:
df1 = pd.DataFrame({'A': ['A0','A1','A2','A3'],
                   'B': ['B0','B1','B2','B3'],
                   'C': ['C0','C1','C2','C3'],
                   'D': ['D0','D1','D2','D3']},
                  index = [0,1,2,3])

In [218]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [224]:
df2 = pd.DataFrame({'A': ['A4','A5','A6','A7'],
                   'B': ['B4','B5','B6','B7'],
                   'C': ['C4','C5','C6','C7'],
                   'D': ['D4','D5','D6','D7']},
                  index = [4,5,6,7])

In [225]:
df3 = pd.DataFrame({'A': ['A8','A9','A10','A11'],
                   'B': ['B8','B9','B10','B11'],
                   'C': ['C8','C9','C10','C11'],
                   'D': ['D8','D9','D10','D11']},
                  index = [8,9,10,11])

In [226]:
pd.concat([df1, df2, df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [227]:
pd.concat([df1, df2, df3], axis=1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

#### (3) Joining

- index가 다른 데이터프레임을 합칚다. 
- left join (default) : join 함수를 호출핚 데이터프레임(1)의 index 사용 
- right join : join 함수 앆에 매개변수로 사용된 데이터프레임(2)의 index 사용 
- outer : (1),(2) 데이터프레임의 index를 모두 사용 
- inner : (1),(2) 데이터프레임이 모두 가지고 잇는 index 사용

In [232]:
left = pd.DataFrame({'A': ['A0','A1','A2'],
                     'B': ['B0','B1','B2']},
                      index =['K0','K1','K2'])

In [233]:
right = pd.DataFrame({'C': ['C0','C1','C2'],
                      'D': ['D0','D1','D2']},
                       index =['K0','K2','K3'])

In [234]:
left

A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [235]:
right

C   D
K0  C0  D0
K2  C1  D1
K3  C2  D2

In [237]:
left.join(right)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C1   D1

In [236]:
left.join(right, how='outer')

A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C1   D1
K3  NaN  NaN   C2   D2

#### Merging

In [242]:
left = pd.DataFrame({'key' : ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0','A1','A2','A3'],
                     'B': ['B0','B1','B2','B3']})

right = pd.DataFrame({'key' : ['K0', 'K1', 'K2', 'K3'],
                     'C': ['C0','C1','C2','C3'],
                     'D': ['D0','D1','D2','D3']})

In [243]:
left

key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [244]:
right

key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [245]:
pd.merge(left,right, how='inner', on='key')

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

### Data Input and Output

In [246]:
import numpy as np
import pandas as pd

In [247]:
import os
os.getcwd()

'C:\\Users\\ce401-6\\Desktop\\BigCam'

#### (1) read_csv()

In [254]:
iris = pd.read_csv('data/iris_data.csv')

In [255]:
iris.head()

Unnamed: 0  sepal length (cm)  sepal width (cm)  petal length (cm)  \
0           0                5.1               3.5                1.4   
1           1                4.9               3.0                1.4   
2           2                4.7               3.2                1.3   
3           3                4.6               3.1                1.5   
4           4                5.0               3.6                1.4   

   petal width (cm)  
0               0.2  
1               0.2  
2               0.2  
3               0.2  
4               0.2

In [257]:
flights = pd.read_csv('data/flights_data.csv')

In [258]:
flights.head()

year     month  passengers
0  1949   January         112
1  1949  February         118
2  1949     March         132
3  1949     April         129
4  1949       May         121

In [259]:
tips = pd.read_csv('data/tips_data.csv')

In [260]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

#### (2) to_csv()

In [261]:
df.to_csv('iris_data.csv')

In [262]:
df1 = pd.read_csv('iris_data.csv')
df1

Unnamed: 0  Unnamed: 0.1  sepal length (cm)  sepal width (cm)  \
0             0             0                5.1               3.5   
1             1             1                4.9               3.0   
2             2             2                4.7               3.2   
3             3             3                4.6               3.1   
4             4             4                5.0               3.6   
5             5             5                5.4               3.9   
6             6             6                4.6               3.4   
7             7             7                5.0               3.4   
8             8             8                4.4               2.9   
9             9             9                4.9               3.1   
10           10            10                5.4               3.7   
11           11            11                4.8               3.4   
12           12            12                4.8               3.0   
13           13            13                4.3               3.0   
14           14            14                5.8               4.0   
15           15            15                5.7               4.4   
16           16            16                5.4               3.9   
17           17            17                5.1               3.5   
18           18            18                5.7               3.8   
19           19            19                5.1               3.8   
20           20            20                5.4               3.4   
21           21            21                5.1               3.7   
22           22            22                4.6               3.6   
23           23            23                5.1               3.3   
24           24            24                4.8               3.4   
25           25            25                5.0               3.0   
26           26            26                5.0               3.4   
27           27            27                5.2               3.5   
28           28            28                5.2               3.4   
29           29            29                4.7               3.2   
..          ...           ...                ...               ...   
120         120           120                6.9               3.2   
121         121           121                5.6               2.8   
122         122           122                7.7               2.8   
123         123           123                6.3               2.7   
124         124           124                6.7               3.3   
125         125           125                7.2               3.2   
126         126           126                6.2               2.8   
127         127           127                6.1               3.0   
128         128           128                6.4               2.8   
129         129           129                7.2               3.0   
130         130           130                7.4               2.8   
131         131           131                7.9               3.8   
132         132           132                6.4               2.8   
133         133           133                6.3               2.8   
134         134           134                6.1               2.6   
135         135           135                7.7               3.0   
136         136           136                6.3               3.4   
137         137           137                6.4               3.1   
138         138           138                6.0               3.0   
139         139           139                6.9               3.1   
140         140           140                6.7               3.1   
141         141           141                6.9               3.1   
142         142           142                5.8               2.7   
143         143           143                6.8               3.2   
144         144           144                6.7               3.3   
145         145

In [263]:
df.to_csv('iris_data.csv', index = False)

In [264]:
df = pd.read_csv('iris_data.csv')
df

Unnamed: 0  sepal length (cm)  sepal width (cm)  petal length (cm)  \
0             0                5.1               3.5                1.4   
1             1                4.9               3.0                1.4   
2             2                4.7               3.2                1.3   
3             3                4.6               3.1                1.5   
4             4                5.0               3.6                1.4   
5             5                5.4               3.9                1.7   
6             6                4.6               3.4                1.4   
7             7                5.0               3.4                1.5   
8             8                4.4               2.9                1.4   
9             9                4.9               3.1                1.5   
10           10                5.4               3.7                1.5   
11           11                4.8               3.4                1.6   
12           12                4.8               3.0                1.4   
13           13                4.3               3.0                1.1   
14           14                5.8               4.0                1.2   
15           15                5.7               4.4                1.5   
16           16                5.4               3.9                1.3   
17           17                5.1               3.5                1.4   
18           18                5.7               3.8                1.7   
19           19                5.1               3.8                1.5   
20           20                5.4               3.4                1.7   
21           21                5.1               3.7                1.5   
22           22                4.6               3.6                1.0   
23           23                5.1               3.3                1.7   
24           24                4.8               3.4                1.9   
25           25                5.0               3.0                1.6   
26           26                5.0               3.4                1.6   
27           27                5.2               3.5                1.5   
28           28                5.2               3.4                1.4   
29           29                4.7               3.2                1.6   
..          ...                ...               ...                ...   
120         120                6.9               3.2                5.7   
121         121                5.6               2.8                4.9   
122         122                7.7               2.8                6.7   
123         123                6.3               2.7                4.9   
124         124                6.7               3.3                5.7   
125         125                7.2               3.2                6.0   
126         126                6.2               2.8                4.8   
127         127                6.1               3.0                4.9   
128         128                6.4               2.8                5.6   
129         129                7.2               3.0                5.8   
130         130                7.4               2.8                6.1   
131         131                7.9               3.8                6.4   
132         132                6.4               2.8                5.6   
133         133                6.3               2.8                5.1   
134         134                6.1               2.6                5.6   
135         135                7.7               3.0                6.1   
136         136                6.3               3.4                5.6   
137         137                6.4               3.1                5.5   
138         138                6.0               3.0                4.8   
139         139                6.9               3.1                5.4   
140         140                6.7               3.1                5.6   
141         141               

##### 실습 

In [268]:
iris.describe()

Unnamed: 0  sepal length (cm)  sepal width (cm)  petal length (cm)  \
count  150.000000         150.000000        150.000000         150.000000   
mean    74.500000           5.843333          3.054000           3.758667   
std     43.445368           0.828066          0.433594           1.764420   
min      0.000000           4.300000          2.000000           1.000000   
25%     37.250000           5.100000          2.800000           1.600000   
50%     74.500000           5.800000          3.000000           4.350000   
75%    111.750000           6.400000          3.300000           5.100000   
max    149.000000           7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.198667  
std            0.763161  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

##### Excel

In [269]:
iris.to_excel('Excel_Sample.xlsx', sheet_name = 'Sheet1')

##### HTML

# # Matplotlib

시각화

*** 변수 확인하기

http://versusall.tistory.com/entry/Jupyter-Notebook-3-%EB%B3%80%EC%88%98-%EB%B3%B4%EA%B8%B0Variable-viewer

In [206]:
whos

Variable         Type         Data/Info
---------------------------------------
EXAM             ndarray      3x2: 6 elems, type `int32`, 24 bytes
Myvariable       list         n=3
a                list         n=5
arr              ndarray      3: 3 elems, type `int32`, 12 bytes
b                int          7
calculate        function     <function calculate at 0x00000000045DB1E0>
d                dict         n=3
data             dict         n=3
df               DataFrame      Company   Person  Sales<...>5      FB    Sarah    350
exam             ndarray      2x3: 6 elems, type `int32`, 24 bytes
exam1            list         n=10
exam2            list         n=10
exam3            list         n=10
exam4            list         n=10
exam5            list         n=3
flotV            list         n=3
gugudan          str          5
ham              list         n=2
i                int          1
labels           list         n=3
mylist           list         n=3
np               mod